<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, RouterLink } from "vue-router";
import { marked, Renderer } from "marked";
import { useHead } from "@unhead/vue";

import {
  apiDocPages,
  apiDocBySlug,
  apiDocNav,
  navSlugs,
} from "@/data/api-docs-loader";
import {
  ensureHighlighter,
  highlightCode,
} from "@/composables/useHighlighter";
import {
  getCrossRef,
  getTotalBlastRadius,
  getAffectedRepos,
  getBlastRadiusColor,
  getBlastRadiusBg,
  type CrossRefData,
} from "@/data/api-docs-cross-ref";

useHead({
  title: "API Docs - ComfyUI Frontend Ecosystem",
});

/**
 * ApiDocs — Swagger-style API reference for @comfyorg/extension-api,
 * generated by P2's TypeDoc → Mintlify-MDX docgen pipeline.
 *
 * Layout: left sidebar (grouped nav from nav-snippet.json) + main pane
 * (rendered markdown of the selected page).
 *
 * Routes: /api-docs (defaults to "index") and /api-docs/:slug.
 */
const route = useRoute();
const highlighterReady = ref(false);

// Load syntax highlighter on mount
onMounted(async () => {
  await ensureHighlighter();
  highlighterReady.value = true;
});

const currentSlug = computed<string>(() => {
  const s = String(route.params.slug ?? "index");
  return s.toLowerCase();
});

const currentPage = computed(() => apiDocBySlug[currentSlug.value]);

// Pages that exist on disk but are not in the nav snippet — show under "Other".
const uncategorizedPages = computed(() =>
  apiDocPages
    .filter((p) => !navSlugs.has(p.slug))
    .map((p) => ({ slug: p.slug, title: p.sidebarTitle ?? p.title })),
);

// Custom renderer with syntax highlighting
const renderer = new Renderer();
renderer.code = ({ text, lang }) => {
  const language = lang || "typescript";
  return highlightCode(text, language);
};

// Configure marked: GFM tables, code blocks with syntax highlighting.
marked.setOptions({ gfm: true, breaks: false });
marked.use({ renderer });

/**
 * Map from type names (PascalCase titles) to their slugs.
 * Used to auto-link type references in rendered code snippets.
 */
const typeNameToSlug: Map<string, string> = new Map(
  apiDocPages
    .filter((p) => p.slug !== "index") // Skip index page
    .map((p) => [p.title, p.slug])
);

/**
 * Post-process rendered HTML to hyperlink type names in inline <code> elements.
 * Targets standalone `<code>TypeName</code>` outside of <pre>/<shiki> blocks.
 * Avoids breaking shiki syntax highlighting by only targeting inline code.
 */
function hyperlinkTypeNames(html: string, currentPageSlug: string): string {
  // Build regex pattern from all type names (sorted by length desc to match longer names first)
  const typeNames = [...typeNameToSlug.keys()].sort(
    (a, b) => b.length - a.length
  );
  if (typeNames.length === 0) return html;

  // Pattern: <code>TypeName</code> not inside <a> or <pre>
  // We use a two-pass approach:
  // 1. Find inline <code> elements (not inside pre/shiki)
  // 2. Replace type names within them

  // Match inline code: <code>content</code> that's NOT inside <pre> or already linked
  // Strategy: split on <pre>...</pre> blocks, process non-pre sections only
  const preSections = html.split(/(<pre[\s\S]*?<\/pre>|<div class="shiki[\s\S]*?<\/div>)/g);

  return preSections
    .map((section) => {
      // Skip pre/shiki blocks entirely
      if (section.startsWith("<pre") || section.startsWith('<div class="shiki')) {
        return section;
      }

      // Process inline <code> elements
      return section.replace(
        /<code>([^<]+)<\/code>/g,
        (match, content: string) => {
          // Check if this code element is already inside an anchor
          // We can't easily check context, so we check if content matches a type name exactly
          const trimmed = content.trim();

          // Don't link the current page to itself
          const slug = typeNameToSlug.get(trimmed);
          if (!slug || slug === currentPageSlug) {
            return match;
          }

          // Wrap in anchor link
          return `<a href="/api-docs/${slug}" class="api-type-link"><code>${content}</code></a>`;
        }
      );
    })
    .join("");
}

const renderedBody = computed<string>(() => {
  // Re-compute when highlighter becomes ready
  void highlighterReady.value;

  const page = currentPage.value;
  if (!page) return "";
  // Rewrite Mintlify-style relative links `./otherpage` -> our router path.
  // Pattern: ](./slug) or ](./slug#anchor)
  const rewritten = page.body.replace(
    /\]\(\.\/([a-zA-Z0-9_-]+)(#[^)]+)?\)/g,
    (_m, slug: string, anchor?: string) =>
      `](/api-docs/${slug.toLowerCase()}${anchor ?? ""})`,
  );
  const html = marked.parse(rewritten) as string;
  // Post-process to hyperlink type names in inline code elements
  return hyperlinkTypeNames(html, currentSlug.value);
});

const totalPages = apiDocPages.length;

/** Extract GitHub source link from rendered body (if present) */
const sourceLink = computed(() => {
  const page = currentPage.value;
  if (!page) return null;
  // Match "Defined in: [path](url)" pattern from TypeDoc output
  // e.g. "Defined in: [src/types/nodeIdentification.ts:96](https://github.com/...)"
  const match = page.body.match(
    /Defined in: \[([^\]]+)\]\((https:\/\/github\.com\/[^)]+)\)/
  );
  if (!match) return null;

  // Parse file path and line number
  const fullPath = match[1]; // e.g. "src/types/nodeIdentification.ts:96"
  const [filePath, lineStr] = fullPath.split(":");
  const line = lineStr ? parseInt(lineStr, 10) : undefined;

  return {
    path: fullPath,
    filePath,
    line,
    url: match[2]
  };
});

/** Build PR diff URL that jumps to the file (and line if available) */
const prReviewUrl = computed(() => {
  const base = "https://github.com/Comfy-Org/ComfyUI_frontend/pull/12142/files";
  const src = sourceLink.value;
  if (!src?.filePath) return base;

  // Use file filter to show only this file in the diff
  const encoded = encodeURIComponent(src.filePath);
  return `${base}?file-filters[]=${encoded}`;
});

/** Cross-reference to v1 patterns and behavior categories */
const crossRef = computed<CrossRefData | null>(() => {
  return getCrossRef(currentSlug.value);
});

const totalBlastRadius = computed(() => {
  return crossRef.value ? getTotalBlastRadius(crossRef.value) : 0;
});

const affectedRepos = computed(() => {
  return crossRef.value ? getAffectedRepos(crossRef.value) : [];
});

/** Extension API PRs for quick navigation */
const extensionApiPRs = [
  { num: 12142, label: "foundation", status: "open" },
  { num: 12143, label: "pkg", status: "open" },
  { num: 12144, label: "ext", status: "open" },
  { num: 12145, label: "tf", status: "open" },
];
</script>

<template>
  <article class="mx-auto max-w-7xl px-4 py-6">
    <header class="mb-6 space-y-3">
      <div class="flex items-start justify-between gap-4">
        <div class="space-y-1">
          <h1 class="text-2xl font-semibold text-zinc-900 dark:text-zinc-100">
            @comfyorg/extension-api — API Reference
          </h1>
          <p class="text-sm text-zinc-600 dark:text-zinc-400">
            TypeScript API reference for ComfyUI custom node extensions. Generated
            by TypeDoc + typedoc-plugin-markdown via the P2 docgen pipeline.
          </p>
          <p class="text-xs text-zinc-500 dark:text-zinc-500">
            {{ totalPages }} pages · synced from
            <code class="font-mono">packages/extension-api/docs-build/mintlify</code>
          </p>
        </div>
        <!-- PR quick-nav buttons -->
        <div class="flex flex-col gap-2">
          <span class="text-[10px] uppercase tracking-wide text-zinc-500 dark:text-zinc-400">Extension API PRs</span>
          <div class="flex flex-wrap gap-1.5">
            <a
              v-for="pr in extensionApiPRs"
              :key="pr.num"
              :href="`https://github.com/Comfy-Org/ComfyUI_frontend/pull/${pr.num}`"
              target="_blank"
              rel="noopener"
              class="inline-flex items-center gap-1.5 rounded-md border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-2.5 py-1.5 text-xs font-medium hover:bg-zinc-50 dark:hover:bg-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-600 transition-colors"
              :title="`Open PR #${pr.num} (${pr.label})`"
            >
              <span class="text-zinc-500">#{{ pr.num }}</span>
              <span class="text-zinc-900 dark:text-zinc-100">{{ pr.label }}</span>
            </a>
          </div>
          <a
            :href="prReviewUrl"
            target="_blank"
            rel="noopener"
            class="inline-flex items-center justify-center gap-1.5 rounded-md bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 text-xs font-medium transition-colors"
            :title="sourceLink ? `Review changes to ${sourceLink.filePath}` : 'Review PR #12142 diff'"
          >
            <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
            </svg>
            {{ sourceLink ? 'Review This File' : 'Start PR Review' }}
          </a>
        </div>
      </div>
    </header>

    <div class="grid grid-cols-1 lg:grid-cols-[260px_minmax(0,1fr)] gap-6">
      <!-- Sidebar nav -->
      <nav
        class="lg:sticky lg:top-4 lg:self-start lg:max-h-[calc(100vh-2rem)] lg:overflow-y-auto pr-2 text-sm"
        aria-label="API docs navigation"
      >
        <ol class="space-y-4">
          <li v-for="group in apiDocNav" :key="group.group">
            <div
              class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-1"
            >
              {{ group.group }}
            </div>
            <ul class="space-y-0.5">
              <li v-for="p in group.pages" :key="p.slug">
                <RouterLink
                  :to="`/api-docs/${p.slug}`"
                  class="block rounded px-2 py-1 font-mono text-xs hover:bg-zinc-100 dark:hover:bg-zinc-800"
                  :class="{
                    'bg-zinc-200 dark:bg-zinc-700 text-zinc-900 dark:text-zinc-100 font-semibold':
                      p.slug === currentSlug,
                    'text-zinc-700 dark:text-zinc-300':
                      p.slug !== currentSlug,
                  }"
                >
                  {{ p.title }}
                </RouterLink>
              </li>
            </ul>
          </li>
          <li v-if="uncategorizedPages.length > 0">
            <div
              class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400 mb-1"
            >
              Other
            </div>
            <ul class="space-y-0.5">
              <li v-for="p in uncategorizedPages" :key="p.slug">
                <RouterLink
                  :to="`/api-docs/${p.slug}`"
                  class="block rounded px-2 py-1 font-mono text-xs hover:bg-zinc-100 dark:hover:bg-zinc-800"
                  :class="{
                    'bg-zinc-200 dark:bg-zinc-700 text-zinc-900 dark:text-zinc-100 font-semibold':
                      p.slug === currentSlug,
                    'text-zinc-700 dark:text-zinc-300':
                      p.slug !== currentSlug,
                  }"
                >
                  {{ p.title }}
                </RouterLink>
              </li>
            </ul>
          </li>
        </ol>
      </nav>

      <!-- Main pane -->
      <main class="min-w-0">
        <div
          v-if="!currentPage"
          class="rounded-md border border-amber-200 bg-amber-50 dark:bg-amber-900/30 p-4 text-sm"
        >
          No API doc page with slug
          <code class="font-mono">{{ currentSlug }}</code>.
        </div>
        <template v-else>
          <header class="mb-4 space-y-2">
            <div class="flex items-start justify-between gap-4">
              <div class="space-y-1">
                <div
                  v-if="currentPage.icon"
                  class="inline-block rounded bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 text-[10px] font-mono uppercase text-zinc-600 dark:text-zinc-400"
                >
                  {{ currentPage.icon }}
                </div>
                <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">
                  {{ currentPage.title }}
                </h2>
                <p
                  v-if="currentPage.description"
                  class="text-sm text-zinc-600 dark:text-zinc-400"
                >
                  {{ currentPage.description }}
                </p>
              </div>
              <!-- Source + Review buttons -->
              <div v-if="sourceLink" class="flex flex-col gap-2 shrink-0">
                <a
                  :href="sourceLink.url"
                  target="_blank"
                  rel="noopener"
                  class="inline-flex items-center justify-center gap-1.5 rounded-md border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-3 py-1.5 text-xs font-medium hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
                  :title="`View source: ${sourceLink.path}`"
                >
                  <svg class="w-3.5 h-3.5 text-zinc-500" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>
                  </svg>
                  <span class="text-zinc-700 dark:text-zinc-300">View Source</span>
                </a>
                <a
                  :href="prReviewUrl"
                  target="_blank"
                  rel="noopener"
                  class="inline-flex items-center justify-center gap-1.5 rounded-md bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 text-xs font-medium transition-colors"
                  :title="`Review changes to ${sourceLink.filePath} in PR #12142`"
                >
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                  <span>Review in PR</span>
                </a>
              </div>
            </div>
          </header>

          <!-- Cross-reference: Related patterns & blast radius -->
          <div
            v-if="crossRef"
            class="mb-6 rounded-lg border border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800/50 p-4"
          >
            <div class="flex items-start justify-between gap-4 mb-3">
              <div>
                <h3 class="text-sm font-semibold text-zinc-900 dark:text-zinc-100 mb-1">
                  Migration Impact
                </h3>
                <p v-if="crossRef.migrationNote" class="text-xs text-zinc-600 dark:text-zinc-400">
                  {{ crossRef.migrationNote }}
                </p>
              </div>
              <!-- Blast radius gauge -->
              <div class="flex items-center gap-2">
                <div class="relative h-5 w-24 rounded-full bg-zinc-200 dark:bg-zinc-700 overflow-hidden">
                  <div
                    class="absolute inset-y-0 left-0 rounded-full transition-all"
                    :class="{
                      'bg-green-500': totalBlastRadius < 3,
                      'bg-yellow-500': totalBlastRadius >= 3 && totalBlastRadius < 5,
                      'bg-red-500': totalBlastRadius >= 5
                    }"
                    :style="{ width: `${Math.min(totalBlastRadius / 10 * 100, 100)}%` }"
                  />
                  <span class="absolute inset-0 flex items-center justify-center text-[10px] font-bold text-white drop-shadow-sm">
                    {{ totalBlastRadius.toFixed(1) }}
                  </span>
                </div>
              </div>
            </div>

            <!-- Related patterns -->
            <div v-if="crossRef.patterns.length > 0" class="mb-3">
              <div class="text-[10px] uppercase tracking-wide text-zinc-500 dark:text-zinc-400 mb-1.5">
                Replaces v1 Patterns
              </div>
              <div class="flex flex-wrap gap-1.5">
                <RouterLink
                  v-for="p in crossRef.patterns.slice(0, 5)"
                  :key="p.pattern_id"
                  :to="`/patterns/${p.pattern_id}`"
                  class="inline-flex items-center gap-1 rounded border border-zinc-200 dark:border-zinc-600 bg-white dark:bg-zinc-900 px-2 py-1 text-[11px] hover:border-zinc-400 dark:hover:border-zinc-500 transition-colors"
                  :title="p.name"
                >
                  <span class="font-mono font-medium text-zinc-700 dark:text-zinc-300">{{ p.pattern_id }}</span>
                  <span
                    class="rounded px-1 py-0.5 text-[9px] font-medium"
                    :class="getBlastRadiusBg(p.blast_radius) + ' ' + getBlastRadiusColor(p.blast_radius)"
                  >
                    {{ p.blast_radius.toFixed(1) }}
                  </span>
                </RouterLink>
              </div>
            </div>

            <!-- Behavior categories -->
            <div v-if="crossRef.categories.length > 0" class="mb-3">
              <div class="text-[10px] uppercase tracking-wide text-zinc-500 dark:text-zinc-400 mb-1.5">
                Behavior Categories
              </div>
              <div class="flex flex-wrap gap-1.5">
                <RouterLink
                  v-for="c in crossRef.categories"
                  :key="c.category_id"
                  :to="`/behavior-categories/${c.category_id}`"
                  class="inline-flex items-center gap-1 rounded border border-zinc-200 dark:border-zinc-600 bg-white dark:bg-zinc-900 px-2 py-1 text-[11px] hover:border-zinc-400 dark:hover:border-zinc-500 transition-colors"
                  :title="c.intent"
                >
                  <span class="font-mono font-medium text-zinc-700 dark:text-zinc-300">{{ c.category_id }}</span>
                  <span class="text-zinc-500 dark:text-zinc-400 truncate max-w-[150px]">{{ c.name }}</span>
                </RouterLink>
              </div>
            </div>

            <!-- Affected repos mini-list -->
            <div v-if="affectedRepos.length > 0">
              <div class="text-[10px] uppercase tracking-wide text-zinc-500 dark:text-zinc-400 mb-1.5">
                Top Affected Repos
              </div>
              <div class="flex flex-wrap gap-x-3 gap-y-1">
                <a
                  v-for="r in affectedRepos"
                  :key="r.repo"
                  :href="`https://github.com/${r.repo}`"
                  target="_blank"
                  rel="noopener"
                  class="inline-flex items-center gap-1 text-[11px] text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
                >
                  <span class="font-mono">{{ r.repo.split('/')[1] }}</span>
                  <span class="text-zinc-400 dark:text-zinc-500">{{ (r.stars / 1000).toFixed(1) }}k</span>
                </a>
              </div>
            </div>
          </div>

          <!-- eslint-disable-next-line vue/no-v-html -- rendered from trusted in-tree TypeDoc output -->
          <div class="api-doc-prose" v-html="renderedBody" />
        </template>
      </main>
    </div>
  </article>
</template>

<style scoped>
/* Lightweight typography for the rendered markdown — close enough to a
   "docs page" feel without pulling in @tailwindcss/typography. Using plain
   CSS rather than @apply because Tailwind v4 scoped styles don't see the
   project theme without an explicit @reference directive. */
.api-doc-prose :deep(h1) {
  margin: 2rem 0 0.75rem;
  font-size: 1.5rem;
  font-weight: 600;
  color: rgb(24 24 27);
}
.api-doc-prose :deep(h2) {
  margin: 2rem 0 0.75rem;
  font-size: 1.25rem;
  font-weight: 600;
  color: rgb(24 24 27);
}
.api-doc-prose :deep(h3) {
  margin: 1.5rem 0 0.5rem;
  font-size: 1rem;
  font-weight: 600;
  color: rgb(24 24 27);
}
.api-doc-prose :deep(p) {
  margin: 0.75rem 0;
  font-size: 0.875rem;
  line-height: 1.6;
  color: rgb(63 63 70);
}
.api-doc-prose :deep(a) {
  color: rgb(29 78 216);
  text-decoration: none;
}
.api-doc-prose :deep(a:hover) {
  text-decoration: underline;
}
/* Auto-linked type names in inline code */
.api-doc-prose :deep(a.api-type-link) {
  text-decoration: none;
}
.api-doc-prose :deep(a.api-type-link code) {
  color: rgb(29 78 216);
  border-bottom: 1px dashed rgb(147 197 253);
}
.api-doc-prose :deep(a.api-type-link:hover code) {
  border-bottom-style: solid;
}
.api-doc-prose :deep(ul),
.api-doc-prose :deep(ol) {
  margin: 0.75rem 0;
  padding-left: 1.25rem;
  font-size: 0.875rem;
  color: rgb(63 63 70);
}
.api-doc-prose :deep(ul) {
  list-style: disc;
}
.api-doc-prose :deep(ol) {
  list-style: decimal;
}
.api-doc-prose :deep(li) {
  margin: 0.25rem 0;
  line-height: 1.5;
}
.api-doc-prose :deep(code) {
  border-radius: 4px;
  background: rgb(244 244 245);
  padding: 1px 4px;
  font-family: ui-monospace, SFMono-Regular, monospace;
  font-size: 11px;
  color: rgb(39 39 42);
}
.api-doc-prose :deep(pre),
.api-doc-prose :deep(.shiki) {
  margin: 0.75rem 0;
  overflow-x: auto;
  border-radius: 6px;
  border: 1px solid rgb(228 228 231);
  padding: 12px;
  font-size: 12px;
}
.api-doc-prose :deep(pre code),
.api-doc-prose :deep(.shiki code) {
  background: transparent;
  padding: 0;
  font-size: 12px;
}
/* Placeholder skeleton while shiki loads */
.api-doc-prose :deep(.shiki-placeholder) {
  position: relative;
  color: rgb(113 113 122);
}
.api-doc-prose :deep(.shiki-placeholder)::after {
  content: "";
  position: absolute;
  top: 8px;
  right: 8px;
  width: 12px;
  height: 12px;
  border: 2px solid rgb(212 212 216);
  border-top-color: rgb(113 113 122);
  border-radius: 50%;
  animation: shiki-spin 0.8s linear infinite;
}
@keyframes shiki-spin {
  to { transform: rotate(360deg); }
}
/* Shiki dual-theme support */
.api-doc-prose :deep(.shiki),
.api-doc-prose :deep(.shiki span) {
  color: var(--shiki-light);
  background-color: var(--shiki-light-bg);
}
.api-doc-prose :deep(table) {
  margin: 1rem 0;
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}
.api-doc-prose :deep(th) {
  border-bottom: 1px solid rgb(228 228 231);
  background: rgb(250 250 250);
  padding: 6px 12px;
  text-align: left;
  font-size: 11px;
  font-weight: 600;
  color: rgb(82 82 91);
  text-transform: uppercase;
  letter-spacing: 0.025em;
}
.api-doc-prose :deep(td) {
  border-bottom: 1px solid rgb(244 244 245);
  padding: 6px 12px;
  font-size: 12px;
  color: rgb(63 63 70);
  vertical-align: top;
}
.api-doc-prose :deep(blockquote) {
  margin: 0.75rem 0;
  border-left: 2px solid rgb(212 212 216);
  padding-left: 12px;
  font-size: 0.875rem;
  color: rgb(82 82 91);
}
.api-doc-prose :deep(hr) {
  margin: 1.5rem 0;
  border: 0;
  border-top: 1px solid rgb(228 228 231);
}

/* Dark-mode overrides — keep separate so it's easy to tweak. */
@media (prefers-color-scheme: dark) {
  .api-doc-prose :deep(h1),
  .api-doc-prose :deep(h2),
  .api-doc-prose :deep(h3) {
    color: rgb(244 244 245);
  }
  .api-doc-prose :deep(p),
  .api-doc-prose :deep(ul),
  .api-doc-prose :deep(ol),
  .api-doc-prose :deep(td) {
    color: rgb(212 212 216);
  }
  .api-doc-prose :deep(a) {
    color: rgb(96 165 250);
  }
  /* Auto-linked type names in dark mode */
  .api-doc-prose :deep(a.api-type-link code) {
    color: rgb(96 165 250);
    border-bottom-color: rgb(59 130 246 / 0.5);
  }
  .api-doc-prose :deep(code) {
    background: rgb(39 39 42);
    color: rgb(228 228 231);
  }
  .api-doc-prose :deep(pre),
  .api-doc-prose :deep(.shiki) {
    background: rgb(9 9 11);
    border-color: rgb(39 39 42);
  }
  .api-doc-prose :deep(pre code),
  .api-doc-prose :deep(.shiki code) {
    color: rgb(228 228 231);
  }
  /* Shiki dark theme */
  .api-doc-prose :deep(.shiki),
  .api-doc-prose :deep(.shiki span) {
    color: var(--shiki-dark) !important;
    background-color: transparent !important;
  }
  .api-doc-prose :deep(th) {
    background: rgb(24 24 27);
    color: rgb(161 161 170);
    border-color: rgb(39 39 42);
  }
  .api-doc-prose :deep(td) {
    border-color: rgb(24 24 27);
  }
  .api-doc-prose :deep(blockquote) {
    border-color: rgb(63 63 70);
    color: rgb(161 161 170);
  }
  .api-doc-prose :deep(hr) {
    border-color: rgb(39 39 42);
  }
}
</style>
