/**
 * API docs loader — eager-imports the 53 MDX pages generated by P2's
 * docgen pipeline (`pnpm --filter @comfyorg/extension-api docs:build`)
 * plus the nav snippet, then exposes parsed { slug, title, description,
 * group, body } records for the /api-docs route.
 *
 * Source of truth: ComfyUI_frontend/packages/extension-api/docs-build/mintlify
 * (copied into ./api-docs/ — re-run scripts/refresh-api-docs.sh to update).
 */

import navSnippet from './api-docs/nav-snippet.json'

// Import every MDX as a raw string. Vite's import.meta.glob with `as: 'raw'`
// reads file contents at build time. The eager flag inlines them so the
// composable doesn't need an async boundary.
const rawPages = import.meta.glob('./api-docs/*.mdx', {
  query: '?raw',
  import: 'default',
  eager: true
}) as Record<string, string>

export interface ApiDocPage {
  /** filename stem, lowercased, e.g. "defineextension" */
  slug: string
  /** frontmatter title */
  title: string
  /** frontmatter description */
  description: string
  /** frontmatter icon (Mintlify icon name; we render as a small label) */
  icon?: string
  /** sidebarTitle override, falls back to title */
  sidebarTitle?: string
  /** Markdown body with frontmatter stripped */
  body: string
}

export interface ApiDocNavItem {
  group: string
  pages: { slug: string; title: string }[]
}

function parseFrontmatter(raw: string): {
  meta: Record<string, string>
  body: string
} {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!m) return { meta: {}, body: raw }
  const meta: Record<string, string> = {}
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*"([^"]*)"\s*$/) || line.match(/^(\w+):\s*(\S+)\s*$/)
    if (kv) meta[kv[1]] = kv[2]
  }
  return { meta, body: m[2] }
}

export const apiDocPages: ApiDocPage[] = Object.entries(rawPages)
  .map(([path, raw]) => {
    const slug = path.replace(/^.*\//, '').replace(/\.mdx$/, '')
    const { meta, body } = parseFrontmatter(raw)
    return {
      slug,
      title: meta.title ?? slug,
      description: meta.description ?? '',
      icon: meta.icon,
      sidebarTitle: meta.sidebarTitle,
      body
    }
  })
  .sort((a, b) => a.slug.localeCompare(b.slug))

export const apiDocBySlug: Record<string, ApiDocPage> = Object.fromEntries(
  apiDocPages.map((p) => [p.slug, p])
)

/**
 * Flatten nav-snippet.json into a list of groups. The Mintlify path prefix
 * "extensions/api/" is stripped so we can map directly to local slugs.
 */
interface NavGroup {
  group: string
  pages: (string | NavGroup)[]
}

export const apiDocNav: ApiDocNavItem[] = (() => {
  const out: ApiDocNavItem[] = []
  function walk(group: string, pages: (string | NavGroup)[]) {
    const items: { slug: string; title: string }[] = []
    for (const p of pages) {
      if (typeof p === 'string') {
        const slug = p.replace(/^.*\//, '')
        const page = apiDocBySlug[slug]
        if (page) items.push({ slug, title: page.sidebarTitle ?? page.title })
      } else if (p && typeof p === 'object' && 'group' in p) {
        walk(p.group, p.pages)
      }
    }
    if (items.length > 0) out.push({ group, pages: items })
  }
  const root = navSnippet as unknown as NavGroup
  walk(root.group, root.pages)
  return out
})()

/** All slugs that appear in the nav (used to render "uncategorized" tail). */
export const navSlugs: Set<string> = new Set(apiDocNav.flatMap((g) => g.pages.map((p) => p.slug)))
