import type {
  BehaviorCategoriesFile,
  BehaviorCategory,
  EvidenceRow,
  Pattern,
  PatternFile,
  RollupEntry,
  RollupFile,
  StarCacheEntry,
  StarCacheFile
} from './schema'
/**
 * Data loader: imports pre-parsed JSON touch-points data at build time.
 *
 * Uses native JSON imports instead of YAML parsing to reduce bundle size
 * (removes ~30KB yaml parser) and improve load performance.
 *
 * The data files are generated by the rebuild script from the source YAMLs.
 */
import behaviorCategoriesData from './behavior-categories.json'
import patternsData from './touch-points-database.json'
import rollupData from './touch-points-rollup.json'

import starCacheData from './touch-points-star-cache.json'

// Type assertions for JSON imports
const patternsFile = patternsData as PatternFile
const rollupFile = rollupData as RollupFile
const behaviorCategoriesFile = behaviorCategoriesData as BehaviorCategoriesFile
const starCacheFile = starCacheData as StarCacheFile

export const patterns: Pattern[] = (patternsFile.patterns ?? []).map((p) => ({
  ...p,
  evidence: p.evidence ?? []
}))
export const rollup: RollupEntry[] = rollupFile.patterns ?? []
export const behaviorCategories: BehaviorCategory[] = behaviorCategoriesFile.categories ?? []

/** Star cache entries keyed by repo for O(1) lookup. */
export const starCache: Record<string, StarCacheEntry> = Object.fromEntries(
  (starCacheFile.repos ?? []).map((r) => [r.repo, r])
)

/**
 * Repos in the star cache with at least one star — i.e. real, public,
 * still-extant ComfyUI custom-node packs we are tracking.
 */
export const starredPacks: StarCacheEntry[] = (starCacheFile.repos ?? []).filter(
  (r) => (r.stars ?? 0) > 0
)

/** Rollup entries keyed by pattern_id for O(1) lookup. */
export const rollupByPatternId: Record<string, RollupEntry> = Object.fromEntries(
  rollup.map((r) => [r.pattern_id, r])
)

/** Patterns keyed by pattern_id for O(1) lookup. */
export const patternById: Record<string, Pattern> = Object.fromEntries(
  patterns.map((p) => [p.pattern_id, p])
)

/**
 * Evidence rows grouped by pattern_id with provenance backfilled. Lets
 * consumers flat-map without re-walking the patterns array.
 */
export const evidenceByPatternId: Record<string, EvidenceRow[]> = (() => {
  const out: Record<string, EvidenceRow[]> = {}
  for (const p of patterns) {
    out[p.pattern_id] = p.evidence.map((e) => ({
      ...e,
      pattern_id: e.pattern_id ?? p.pattern_id
    }))
  }
  return out
})()

/** Total evidence-row count per pack (repo). Used by the heatmap to pick top-N. */
export const evidenceCountByPack: Record<string, number> = (() => {
  const out: Record<string, number> = {}
  for (const p of patterns) {
    for (const e of p.evidence) {
      if (!e.repo) continue
      out[e.repo] = (out[e.repo] ?? 0) + 1
    }
  }
  return out
})()

/** Total number of evidence rows across all patterns. */
export const totalEvidenceCount: number = patterns.reduce((acc, p) => acc + p.evidence.length, 0)

export type {
  BehaviorCategory,
  BehaviorExemplar,
  EvidenceRow,
  Pattern,
  RollupEntry,
  StarCacheEntry
} from './schema'
